CREATE OR ALTER PROCEDURE USP_LayDanhSachNhaXe
as
	SELECT * FROM DANHSACHNHAXE;
GO;

CREATE OR ALTER PROCEDURE USP_QuanLyDichVuKhachHangSuDung
as
	SELECT DV.TENDICHVU, DV.GIATIEN, KH.TENKH
	FROM DICHVU DV, PHIEU PH, PHIEUDANGKYDICHVU PHDV, KHACHHANG KH 
	WHERE KH.MAKH = PH.MAKH AND PHDV.MAPHIEU = PH.MAPHIEU AND PHDV.DICHVUSUDUNG = DV.MADICHVU
GO;