CREATE OR ALTER PROCEDURE USP_LayDanhSachNhaXe
as
	SELECT * FROM DANHSACHNHAXE;
GO

CREATE OR ALTER PROCEDURE USP_QuanLyDichVuKhachHangSuDung
as
	SELECT DV.TENDICHVU, DV.GIATIEN, KH.TENKH
	FROM DICHVU DV, PHIEU PH, PHIEUDANGKYDICHVU PHDV, KHACHHANG KH 
	WHERE KH.MAKH = PH.MAKH AND PHDV.MAPHIEU = PH.MAPHIEU AND PHDV.DICHVUSUDUNG = DV.MADICHVU;
GO

CREATE OR ALTER PROCEDURE USP_LayHoaDonKemTenKhachHang @TENKH NVARCHAR(100)
as
	SELECT HD.MAHD AS N'Mã hóa đơn', KH.TENKH AS N'Tên khách hàng', HD.TONGTIEN AS N'Tổng tiền'  
	FROM HOADON HD, KHACHHANG KH 
	WHERE KH.MAKH = HD.MAKH AND KH.TENKH = @TENKH;
GO

CREATE OR ALTER PROCEDURE USP_Update @TINHTRANGLT NVARCHAR(100), @TRANGTHAIVS NVARCHAR(100), @SOPHONG VARCHAR(50)
as
	UPDATE PHONG SET TINHTRANGLT = @TINHTRANGLT, TRANGTHAIVS = @TRANGTHAIVS WHERE SOPHONG = @SOPHONG;
GO

	