USE master
GO

IF DB_ID('QLKHACHSAN') IS NOT NULL ---KIỂM TRA NẾU KHÔNG CÓ CSDL TRÙNG TÊN ĐƯỢC TẠO TRƯỚC ĐÓ
	DROP DATABASE QLKHACHSAN
GO
CREATE DATABASE QLKHACHSAN
GO 
USE QLKHACHSAN 
GO

--- TẠO BẢNG DỮ LIỆU
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(50),
	HOTEN NVARCHAR(100),
	NGAYSINH DATE,
	SODT VARCHAR(50),
	DIACHI NVARCHAR(100),
	CCCD VARCHAR(12),
	CATRUC NVARCHAR(50),
	VAITRO NVARCHAR (50)
	
	CONSTRAINT PK_NHANVIEN
	PRIMARY KEY(MANV)
)

--- DÀNH CHO NHÂN VIÊN LỄ TÂN VÀ NHÂN VIÊN VỆ SINH
CREATE TABLE CHITIETNV
(
	MANV VARCHAR(50),
	TANGHD NVARCHAR(100)
	
	CONSTRAINT PK_CHITIETNV
	PRIMARY KEY(MANV)
)
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(50),
	TENKH NVARCHAR(100),
	DIACHI NVARCHAR(100),
	SODT VARCHAR(50),
	SOFAX VARCHAR(50),
	EMAIL NVARCHAR(100),
	CCCD NVARCHAR(12),
	SOTHE VARCHAR(100),
	HINHTHUCTHANHTOAN NVARCHAR(100)

	CONSTRAINT PK_KHACHHANG
	PRIMARY KEY(MAKH)	
)

CREATE TABLE KHACHHANGNHOM --- KHÁCH HÀNG ĐẠT PHÒNG THEO NHÓM
(	
	MAKH VARCHAR(50),
	TENDOANKHACH NVARCHAR(100),
	SONGUOI DECIMAL,
	NGAYDEN DATE,
	SODEMLUUTRU DECIMAL

	CONSTRAINT PK_KHACHHANGNHOM
	PRIMARY KEY (MAKH)
)
CREATE TABLE THENGANHANG
(
	SOTHE VARCHAR(100),
	TENCHUTHE NVARCHAR(100),
	NGANHANG NVARCHAR(100),
	CHINHANH NVARCHAR(100)

	CONSTRAINT PK_THENGANHANG
	PRIMARY KEY (SOTHE)
)
CREATE TABLE PHONG 
(
	SOPHONG VARCHAR(50),
	LOAIPHONG NVARCHAR(100),
	TINHTRANGLT NVARCHAR(100),
	TRANGTHAIVS NVARCHAR(100),
	MAKHUYENMAI VARCHAR(50)

	CONSTRAINT PK_PHONG
	PRIMARY KEY(SOPHONG)
)
CREATE TABLE HANGCHO
(
	STT DECIMAL,
	MAYC VARCHAR(50),
	NGAYDAT DATE
	
	CONSTRAINT PK_HANGCHO
	PRIMARY KEY (MAYC)
)
CREATE TABLE YEUCAUDATPHONG
(
	MAYC VARCHAR(50),
	MAKH VARCHAR(50),
	SOLUONG DECIMAL

	CONSTRAINT PK_YEUCAUDATPHONG
	PRIMARY KEY(MAYC)
)
CREATE TABLE THONGTINDATPHONG
(
	MADAT VARCHAR(50),
	MAYC VARCHAR(50),
	TRANGTHAI NVARCHAR(100),
	THANHTIEN DECIMAL(10,2),
	NGAYDEN DATE,
	SODEMLUUTRU DECIMAL,
	LOAIPHONG NVARCHAR(100),
	YEUCAUDACBIET NVARCHAR(100)

	CONSTRAINT PK_THONGTINDATPHONG
	PRIMARY KEY(MADAT)
)
CREATE TABLE KHUYENMAITHEOPHONG
(
	MAKHUYENMAI VARCHAR(50),
	SOPHONG VARCHAR(50),
	NOIDUNG NVARCHAR(100)
	
	CONSTRAINT PK_KHUYENMAITHEOPHONG
	PRIMARY KEY(MAKHUYENMAI)
)
CREATE TABLE DANGKYVANCHUYENHANHLY
(
	MADON VARCHAR(50),
	SOLUONG DECIMAL,
	SOPHONG VARCHAR(50)

	CONSTRAINT PK_DANGKYVANCHUYENHANHLY
	PRIMARY KEY(MADON)
)
CREATE TABLE DICHVU
(
	MADICHVU VARCHAR(50),
	TENDICHVU NVARCHAR(100),
	GIATIEN DECIMAL (10,2),
	MOTA NVARCHAR(200),

	CONSTRAINT PK_DICHVU
	PRIMARY KEY (MADICHVU)
)
CREATE TABLE TOURDULICH
(
	MATOUR VARCHAR(50),
	DIADIEM NVARCHAR(100),
	MOTA NVARCHAR(200),
	THOIGIANKHOIHANH DATE,
	DONVILUHANH NVARCHAR(100)

	CONSTRAINT PK_TOURDULICH
	PRIMARY KEY (MATOUR)
)
CREATE TABLE HOADON
(
	MAHD VARCHAR(50),
	MAKH VARCHAR(50),
	TONGTIEN DECIMAL (10,2)
	CONSTRAINT PK_HOADON
	PRIMARY KEY (MAHD)
)
CREATE TABLE CHITIETHOADON
(
	MAHD VARCHAR(50),
	MACT VARCHAR(50),
	NGAYLAP DATE,
	DICHVUSUDUNG VARCHAR(50), --- NỐI VỚI MADICHVU Ở BẢNG DỊCH VỤ
	DONGIA DECIMAL (10,2),
	SOLUONG DECIMAL

)
CREATE TABLE PHIEU
(
	MAPHIEU VARCHAR(50),
	MAKH VARCHAR(50),
	NGAYLAP DATE

	CONSTRAINT PK_PHIEU
	PRIMARY KEY(MAPHIEU)
)
CREATE TABLE PHIEUDANGKYTOUR
(
	MAPHIEU VARCHAR(50),
	TOURTHAMGIA VARCHAR(50), -- MÃ TOUR
	SOLUONGNGUOI DECIMAL,
	HINHTHUCDICHUYEN NVARCHAR(100),
	YEUCAUDACBIET NVARCHAR(100)

	CONSTRAINT PK_PHIEUDANGKYTOUR
	PRIMARY KEY(MAPHIEU)
)

-- PHIẾU ĐĂNG KÝ DỊCH VỤ
CREATE TABLE PHIEUDANGKYDICHVU
(
	MAPHIEU VARCHAR(50),
	NGAYSUDUNG DATE,
	DICHVUSUDUNG VARCHAR(50),

	CONSTRAINT PK_PHIEUDANGKYDICHVU
	PRIMARY KEY(MAPHIEU)
)
CREATE TABLE DANHSACHNHAXE
(
	MANHAXE VARCHAR(50),
	TENNHAXE NVARCHAR(100),
	SODT VARCHAR(50),

	CONSTRAINT PK_DANHSACHNHAXE
	PRIMARY KEY(MANHAXE)
)
CREATE TABLE TAIKHOAN
(
USERNAME VARCHAR(50),
PASS VARCHAR(50),
VAITRO NVARCHAR(50),
MANV VARCHAR(50),


CONSTRAINT PK_TAIKHOAN
PRIMARY KEY(USERNAME,PASS)
)
CREATE TABLE YKIENKHACHHANG
(
MAKH VARCHAR(50),
NGAYLAP DATE,
MOTA VARCHAR

CONSTRAINT MAKH
PRIMARY KEY(MAKH)
)

--- CÀI ĐẶT KHÓA NGOẠI

ALTER TABLE KHACHHANGNHOM --- THÔNG TIN CHI TIẾT CỦA KHÁCH HÀNG ĐẶT PHÒNG THEO ĐOÀN PHẢI ĐƯỢC LƯU TRONG DANH SÁCH KHÁCH HÀNG
ADD CONSTRAINT FK_KHTM_KH
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_TK_NV
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CHITIETNV
ADD CONSTRAINT FK_CHITIETNV_NV
FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)



ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KH_TNGH
FOREIGN KEY (SOTHE) REFERENCES THENGANHANG (SOTHE)



ALTER TABLE YKIENKHACHHANG
ADD CONSTRAINT FK_YKKH_KH
FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)

ALTER TABLE PHIEUDANGKYTOUR
ADD CONSTRAINT FK_PHIEUDANGKYTOUR_PHIEU
FOREIGN KEY (MAPHIEU) REFERENCES PHIEU (MAPHIEU)

ALTER TABLE PHIEUDANGKYDICHVU
ADD CONSTRAINT FK_PHIEUDANGKYDICHVU_PHIEU
FOREIGN KEY (MAPHIEU) REFERENCES PHIEU(MAPHIEU)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CTHD_HD
FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CTHD_DV
FOREIGN KEY (DICHVUSUDUNG) REFERENCES DICHVU(MADICHVU)

ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_KH
FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)


ALTER TABLE HANGCHO
ADD CONSTRAINT FK_HC_YC
FOREIGN KEY (MAYC) REFERENCES YEUCAUDATPHONG(MAYC)

ALTER TABLE YEUCAUDATPHONG
ADD CONSTRAINT FK_YC_KH
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE THONGTINDATPHONG
ADD CONSTRAINT FK_TT_YC
FOREIGN KEY (MAYC) REFERENCES YEUCAUDATPHONG(MAYC)


ALTER TABLE KHUYENMAITHEOPHONG
ADD CONSTRAINT FK_KM_PHONG
FOREIGN KEY (SOPHONG) REFERENCES PHONG(SOPHONG)


ALTER TABLE PHIEU
ADD CONSTRAINT FK_PHIEU_KH
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)


ALTER TABLE DANGKYVANCHUYENHANHLY
ADD CONSTRAINT FK_DKVCHL_PHONG
FOREIGN KEY (SOPHONG) REFERENCES PHONG(SOPHONG)

-- NHẬP DỮ LIỆU
INSERT NHANVIEN(MANV, HOTEN, NGAYSINH, SODT, DIACHI, CCCD, CATRUC, VAITRO)
VALUES ('NV001', N'Lê Văn Quân', '1973-02-15', '0838126126', N'69 Trịnh Đình Thảo, Phú Trung, Tân Phú, Thành phố Hồ Chí Minh', '782936885101', NULL , N'Lễ Tân'),
	   ('NV002', N'Nguyễn Văn Tuyết', '1979-10-30', '0374080895', N'565 Lạc Long Quân, Phường 10, Tân Bình, Thành phố Hồ Chí Minh', '823326582035', NULL , N'Lễ Tân'),
	   ('NV003', N'Trần Văn Thành', '1980-11-20', '0274010895', N'45 Lê Thánh Tôn, Bến Nghé, Quận 1, Thành phố Hồ Chí Minh', '603167292135', NULL , N'Bellman'),
	   ('NV004', N'Mai Tuấn Khanh', '1978-05-08', '0999712602', N'973 Lũy Bán Bích, Tân Thành, Tân Phú, Thành phố Hồ Chí Minh', '445794292675', NULL , N'Bellman'),
	   ('NV005', N'Bùi Xuân Huy', '1979-10-11', '0397836164', N'1134 Phạm Văn Đồng, Linh Đông, Thành Phố Thủ Đức, Thành phố Hồ Chí Minh', '902270137212', NULL , N'Nhân viên vệ sinh'),
	   ('NV006', N'Vũ Hồng Đức', '1989-02-12', '0897205247', N'740/15A Sư Vạn Hạnh, Phường 12, Quận 10, Thành phố Hồ Chí Minh', '095623791774', NULL , N'Nhân viên kế toán'),
	   ('NV007', N'Đoàn Văn Vui', '1990-01-02', '0523613534', N'B15/13c Ấp 2, Bình Chánh, Thành phố Hồ Chí Minh', '673275174393', NULL , N'Nhân viên kế toán')

INSERT CHITIETNV(MANV, TANGHD)
VALUES ('NV001', N'')

INSERT KHACHHANG(MAKH, TENKH, DIACHI, SODT, SOFAX, EMAIL, CCCD, SOTHE, HINHTHUCTHANHTOAN)
VALUES ('KH001', N'Tôn Thất Bách', N'740/15A Sư Vạn Hạnh, Phường 12, Quận 10, Thành phố Hồ Chí Minh', '0339161316', '+84 24 123 4567', N'yokuneva@yahoo.com', '554926537264','4849860728359294', N'Thẻ tín dụng'),
	   ('KH002', N'Nguyễn Trung Nguyên', N'Hẻm 320 Trần Bình Trọng, Phường 4, Quận 5, Thành phố Hồ Chí Minh', '0999837480', '+84 28 234 5678', N'jasetaylor@yt-google.com', '790856623849', NULL, N'Tiền mặt'),
	   ('KH003', N'Lại An Phú', N'565 Lạc Long Quân, Phường 10, Tân Bình, Thành phố Hồ Chí Minh', '0374080895', '+84 236 345 6789', N'fkuhn@hotmail.com', '058411867415', '4961813447012597', N'Thẻ tín dụng')

INSERT KHACHHANGNHOM(MAKH, TENDOANKHACH, SONGUOI, NGAYDEN, SODEMLUUTRU)
VALUES ('KH003', N'ĐH Khoa học Tự nhiên - ĐHQG TPHCM', 100, )